


    export enum AbiaLGA  {
        AbaNorth = "Aba North",
        AbaSouth = "Aba South",
        Arochukwu = "Arochukwu",
        Bende = "Bende",
        Ikwuano = "Ikwuano",
        IsialaNgwaNorth = "Isiala Ngwa North",
        IsialaNgwaSouth = "Isiala Ngwa South",
        Isuikwuato = "Isuikwuato",
        ObiNgwa = "Obi Ngwa",
        Ohafia = "Ohafia",
        OsisiomaNgwa = "Osisioma Ngwa",
        Ugwunagbo = "Ugwunagbo",
        UkwaEast = "Ukwa East",
        UkwaWest = "Ukwa West",
        UmuahiaNorth = "Umuahia North",
        UmuahiaSouth = "Umuahia South",
        UmuNneochi = "Umu Nneochi"
    }


   export enum AdamawaLGA {
        Demsa = "Demsa",
        Fufore = "Fufore",
        Ganye = "Ganye",
        Girei = "Girei",
        Gombi = "Gombi",
        Guyuk = "Guyuk",
        Hong = "Hong",
        Jada = "Jada",
        Lamurde = "Lamurde",
        Madagali = "Madagali",
        Maiha = "Maiha",
        MayoBelwa = "Mayo-Belwa",
        Michika = "Michika",
        MubiNorth = "Mubi North",
        MubiSouth = "Mubi South",
        Numan = "Numan",
        Shelleng = "Shelleng",
        Song = "Song",
        Toungo = "Toungo",
        YolaNorth = "Yola North",
        YolaSouth = "Yola South"
    }


    export enum AkwaIbomLGA {
        Abak = "Abak",
        EasternObolo = "Eastern Obolo",
        Eket = "Eket",
        EsitEket = "Esit Eket",
        EssienUdim = "Essien Udim",
        EtimEkpo = "Etim Ekpo",
        Etinan = "Etinan",
        Ibeno = "Ibeno",
        IbesikpoAsutan = "Ibesikpo Asutan",
        IbionoIbom = "Ibiono Ibom",
        Ika = "Ika",
        Ikono = "Ikono",
        IkotAbasi = "Ikot Abasi",
        IkotEkpene = "Ikot Ekpene",
        Ini = "Ini",
        Itu = "Itu",
        Mbo = "Mbo",
        MkpatEnin = "Mkpat Enin",
        NsitAtai = "Nsit Atai",
        NsitIbom = "Nsit Ibom",
        NsitUbium = "Nsit Ubium",
        ObotAkara = "Obot Akara",
        Okobo = "Okobo",
        Onna = "Onna",
        Oron = "Oron",
        OrukAnam = "Oruk Anam",
        Ukanafun = "Ukanafun",
        UdungUko = "Udung Uko",
        Uruan = "Uruan",
        UrueOffongOruko = "Urue-Offong/Oruko",
        Uyo = "Uyo"
    }

    export enum AnambraLGA {
        Aguata = "Aguata",
        AnambraEast = "Anambra East",
        AnambraWest = "Anambra West",
        Anaocha = "Anaocha",
        AwkaNorth = "Awka North",
        AwkaSouth = "Awka South",
        Ayamelum = "Ayamelum",
        Dunukofia = "Dunukofia",
        Ekwusigo = "Ekwusigo",
        IdemiliNorth = "Idemili North",
        IdemiliSouth = "Idemili South",
        Ihiala = "Ihiala",
        Njikoka = "Njikoka",
        NnewiNorth = "Nnewi North",
        NnewiSouth = "Nnewi South",
        Ogbaru = "Ogbaru",
        OnitshaNorth = "Onitsha North",
        OnitshaSouth = "Onitsha South",
        OrumbaNorth = "Orumba North",
        OrumbaSouth = "Orumba South",
        Oyi = "Oyi"
    }


    export enum BauchiLGA {
        Alkaleri = "Alkaleri",
        Bauchi = "Bauchi",
        Bogoro = "Bogoro",
        Damban = "Damban",
        Darazo = "Darazo",
        Dass = "Dass",
        Gamawa = "Gamawa",
        Ganjuwa = "Ganjuwa",
        Giade = "Giade",
        ItasGadau = "Itas/Gadau",
        Jamaare = "Jama'are",
        Katagum = "Katagum",
        Kirfi = "Kirfi",
        Misau = "Misau",
        Ningi = "Ningi",
        Shira = "Shira",
        TafawaBalewa = "Tafawa Balewa",
        Toro = "Toro",
        Warji = "Warji",
        Zaki = "Zaki"
    }

    export enum BayelsaLGA {
        Brass = "Brass",
        Ekeremor = "Ekeremor",
        KolokumaOpokuma = "Kolokuma/Opokuma",
        Nembe = "Nembe",
        Ogbia = "Ogbia",
        Sagbama = "Sagbama",
        SouthernIjaw = "Southern Ijaw",
        Yenagoa = "Yenagoa"
    }

    export enum BenueLGA {
        Ado = "Ado",
        Agatu = "Agatu",
        Apa = "Apa",
        Buruku = "Buruku",
        Gboko = "Gboko",
        Guma = "Guma",
        GwerEast = "Gwer East",
        GwerWest = "Gwer West",
        KatsinaAla = "Katsina-Ala",
        Konshisha = "Konshisha",
        Kwande = "Kwande",
        Logo = "Logo",
        Makurdi = "Makurdi",
        Obi = "Obi",
        Ogbadibo = "Ogbadibo",
        Ohimini = "Ohimini",
        Oju = "Oju",
        Okpokwu = "Okpokwu",
        Otukpo = "Otukpo",
        Tarka = "Tarka",
        Ukum = "Ukum",
        Ushongo = "Ushongo",
        Vandeikya = "Vandeikya"
    }

    export enum BornoLGA {
        Abadam = "Abadam",
        AskiraUba = "Askira/Uba",
        Bama = "Bama",
        Bayo = "Bayo",
        Biu = "Biu",
        Chibok = "Chibok",
        Damboa = "Damboa",
        Dikwa = "Dikwa",
        Gubio = "Gubio",
        Guzamala = "Guzamala",
        Gwoza = "Gwoza",
        Hawul = "Hawul",
        Jere = "Jere",
        Kaga = "Kaga",
        KalaBalge = "Kala/Balge",
        Konduga = "Konduga",
        Kukawa = "Kukawa",
        KwayaKusar = "Kwaya Kusar",
        Mafa = "Mafa",
        Magumeri = "Magumeri",
        Maiduguri = "Maiduguri",
        Marte = "Marte",
        Mobbar = "Mobbar",
        Monguno = "Monguno",
        Ngala = "Ngala",
        Nganzai = "Nganzai",
        Shani = "Shani"
    }

    export enum CrossRiverLGA {
        Abi = "Abi",
        Akamkpa = "Akamkpa",
        Akpabuyo = "Akpabuyo",
        Bakassi = "Bakassi",
        Bekwarra = "Bekwarra",
        Biase = "Biase",
        Boki = "Boki",
        CalabarMunicipal = "Calabar Municipal",
        CalabarSouth = "Calabar South",
        Etung = "Etung",
        Ikom = "Ikom",
        Obanliku = "Obanliku",
        Obubra = "Obubra",
        Obudu = "Obudu",
        Odukpani = "Odukpani",
        Ogoja = "Ogoja",
        Yakurr = "Yakurr",
        Yala = "Yala"
    }

    export enum DeltaLGA {
        AniochaNorth = "Aniocha North",
        AniochaSouth = "Aniocha South",
        Bomadi = "Bomadi",
        Burutu = "Burutu",
        EthiopeEast = "Ethiope East",
        EthiopeWest = "Ethiope West",
        IkaNorthEast = "Ika North East",
        IkaSouth = "Ika South",
        IsokoNorth = "Isoko North",
        IsokoSouth = "Isoko South",
        NdokwaEast = "Ndokwa East",
        NdokwaWest = "Ndokwa West",
        Okpe = "Okpe",
        OshimiliNorth = "Oshimili North",
        OshimiliSouth = "Oshimili South",
        Patani = "Patani",
        Sapele = "Sapele",
        Udu = "Udu",
        UghelliNorth = "Ughelli North",
        UghelliSouth = "Ughelli South",
        Ukwuani = "Ukwuani",
        Uvwie = "Uvwie",
        WarriNorth = "Warri North",
        WarriSouth = "Warri South",
        WarriSouthWest = "Warri South West"
    }


    export enum EbonyiLGA{
        Abakaliki = "Abakaliki",
        AfikpoNorth = "Afikpo North",
        AfikpoSouth = "Afikpo South",
        Ebonyi = "Ebonyi",
        EzzaNorth = "Ezza North",
        EzzaSouth = "Ezza South",
        Ikwo = "Ikwo",
        Ishielu = "Ishielu",
        Ivo = "Ivo",
        Izzi = "Izzi",
        Ohaozara = "Ohaozara",
        Ohaukwu = "Ohaukwu",
        Onicha = "Onicha"
    }

    export enum EdoLGA {
        AkokoEdo = "Akoko Edo",
        Egor = "Egor",
        EsanCentral = "Esan Central",
        EsanNorthEast = "Esan North-East",
        EsanSouthEast = "Esan South-East",
        EsanWest = "Esan West",
        EtsakoCentral = "Etsako Central",
        EtsakoEast = "Etsako East",
        EtsakoWest = "Etsako West",
        Igueben = "Igueben",
        IkpobaOkha = "Ikpoba-Okha",
        Oredo = "Oredo",
        Orhionmwon = "Orhionmwon",
        OviaNorthEast = "Ovia North-East",
        OviaSouthWest = "Ovia South-West",
        OwanEast = "Owan East",
        OwanWest = "Owan West",
        Uhunmwonde = "Uhunmwonde"
    }

    export enum EkitiLGA  {
        AdoEkiti = "Ado Ekiti",
        Efon = "Efon",
        EkitiEast = "Ekiti East",
        EkitiSouthWest = "Ekiti South-West",
        EkitiWest = "Ekiti West",
        Emure = "Emure",
        IdoOsi = "Ido-Osi",
        Ijero = "Ijero",
        Ikere = "Ikere",
        Ikole = "Ikole",
        Ilejemeje = "Ilejemeje",
        IrepodunIfelodun = "Irepodun/Ifelodun",
        IseOrun = "Ise/Orun",
        Moba = "Moba",
        Oye = "Oye"
    }

    export enum EnuguLGA {
        Aninri = "Aninri",
        Awgu = "Awgu",
        EnuguEast = "Enugu East",
        EnuguNorth = "Enugu North",
        EnuguSouth = "Enugu South",
        Ezeagu = "Ezeagu",
        IgboEtiti = "Igbo Etiti",
        IgboEzeNorth = "Igbo Eze North",
        IgboEzeSouth = "Igbo Eze South",
        IsiUzo = "Isi Uzo",
        NkanuEast = "Nkanu East",
        NkanuWest = "Nkanu West",
        Nsukka = "Nsukka",
        OjiRiver = "Oji River",
        Udenu = "Udenu",
        Udi = "Udi",
        UzoUwani = "Uzo-Uwani"
    }

    export enum GombeLGA {
        Akko = "Akko",
        Balanga = "Balanga",
        Billiri = "Billiri",
        Dukku = "Dukku",
        Funakaye = "Funakaye",
        Gombe = "Gombe",
        Kaltungo = "Kaltungo",
        Kwami = "Kwami",
        Nafada = "Nafada",
        Shongom = "Shongom",
        YamaltuDeba = "Yamaltu/Deba"
    }

    export enum ImoLGA {
        AbohMbaise = "Aboh Mbaise",
        AhiazuMbaise = "Ahiazu Mbaise",
        EhimeMbano = "Ehime Mbano",
        Ezinihitte = "Ezinihitte",
        IdeatoNorth = "Ideato North",
        IdeatoSouth = "Ideato South",
        IhitteUboma = "Ihitte/Uboma",
        Ikeduru = "Ikeduru",
        IsialaMbano = "Isiala Mbano",
        Isu = "Isu",
        Mbaitoli = "Mbaitoli",
        NgorOkpala = "Ngor Okpala",
        Njaba = "Njaba",
        Nkwerre = "Nkwerre",
        Nwangele = "Nwangele",
        Obowo = "Obowo",
        Oguta = "Oguta",
        OhajiEgbema = "Ohaji/Egbema",
        Okigwe = "Okigwe",
        Onuimo = "Onuimo",
        Orlu = "Orlu",
        Orsu = "Orsu",
        OruEast = "Oru East",
        OruWest = "Oru West",
        OwerriMunicipal = "Owerri Municipal",
        OwerriNorth = "Owerri North",
        OwerriWest = "Owerri West"
    }

    export enum JigawaLGA {
        Auyo = "Auyo",
        Babura = "Babura",
        Biriniwa = "Biriniwa",
        BirninKudu = "Birnin Kudu",
        Buji = "Buji",
        Dutse = "Dutse",
        Gagarawa = "Gagarawa",
        Garki = "Garki",
        Gumel = "Gumel",
        Guri = "Guri",
        Gwaram = "Gwaram",
        Gwiwa = "Gwiwa",
        Hadejia = "Hadejia",
        Jahun = "Jahun",
        KafinHausa = "Kafin Hausa",
        Kaugama = "Kaugama",
        Kazaure = "Kazaure",
        KiriKasama = "Kiri Kasama",
        Kiyawa = "Kiyawa",
        Maigatari = "Maigatari",
        MalamMadori = "Malam Madori",
        Miga = "Miga",
        Ringim = "Ringim",
        Roni = "Roni",
        SuleTankarkar = "Sule Tankarkar",
        Taura = "Taura",
        Yankwashi = "Yankwashi"
    }

    export enum KadunaLGA {
        BirninGwari = "Birnin Gwari",
        Chikun = "Chikun",
        Giwa = "Giwa",
        Igabi = "Igabi",
        Ikara = "Ikara",
        Jaba = "Jaba",
        Jema = "Jema'a",
        Kachia = "Kachia",
        KadunaNorth = "Kaduna North",
        KadunaSouth = "Kaduna South",
        Kagarko = "Kagarko",
        Kajuru = "Kajuru",
        Kaura = "Kaura",
        Kauru = "Kauru",
        Kubau = "Kubau",
        Kudan = "Kudan",
        Lere = "Lere",
        Makarfi = "Makarfi",
        SabonGari = "Sabon Gari",
        Sanga = "Sanga",
        Soba = "Soba",
        ZangonKataf = "Zangon Kataf",
        Zaria = "Zaria"
    }

    export enum KanoLGA {
        Ajingi = "Ajingi",
        Albasu = "Albasu",
        Bagwai = "Bagwai",
        Bebeji = "Bebeji",
        Bichi = "Bichi",
        Bunkure = "Bunkure",
        Dala = "Dala",
        Dambatta = "Dambatta",
        DawakinKudu = "Dawakin Kudu",
        DawakinTofa = "Dawakin Tofa",
        Doguwa = "Doguwa",
        Fagge = "Fagge",
        Gabasawa = "Gabasawa",
        Garko = "Garko",
        GarunMallam = "Garun Mallam",
        Gaya = "Gaya",
        Gezawa = "Gezawa",
        Gwale = "Gwale",
        Gwarzo = "Gwarzo",
        Kabo = "Kabo",
        KanoMunicipal = "Kano Municipal",
        Karaye = "Karaye",
        Kibiya = "Kibiya",
        Kiru = "Kiru",
        Kumbotso = "Kumbotso",
        Kunchi = "Kunchi",
        Kura = "Kura",
        Madobi = "Madobi",
        Makoda = "Makoda",
        Minjibir = "Minjibir",
        Nassarawa = "Nassarawa",
        Rano = "Rano",
        RiminGado = "Rimin Gado",
        Rogo = "Rogo",
        Shanono = "Shanono",
        Sumaila = "Sumaila",
        Takai = "Takai",
        Tarauni = "Tarauni",
        Tofa = "Tofa",
        Tsanyawa = "Tsanyawa",
        TudunWada = "Tudun Wada",
        Ungogo = "Ungogo",
        Warawa = "Warawa",
        Wudil = "Wudil"
    }

    export enum KatsinaLGA  {
        Bakori = "Bakori",
        Batagarawa = "Batagarawa",
        Batsari = "Batsari",
        Baure = "Baure",
        Bindawa = "Bindawa",
        Charanchi = "Charanchi",
        Danja = "Danja",
        DanMusa = "Dan Musa",
        Daura = "Daura",
        Dutsi = "Dutsi",
        DutsinMa = "Dutsin-Ma",
        Faskari = "Faskari",
        Funtua = "Funtua",
        Ingawa = "Ingawa",
        Jibia = "Jibia",
        Kafur = "Kafur",
        Kaita = "Kaita",
        Kankara = "Kankara",
        Kankia = "Kankia",
        Katsina = "Katsina",
        Kurfi = "Kurfi",
        Kusada = "Kusada",
        MaiAdua = "Mai'Adua",
        Malumfashi = "Malumfashi",
        Mani = "Mani",
        Mashi = "Mashi",
        Matazu = "Matazu",
        Musawa = "Musawa",
        Rimi = "Rimi",
        Sabuwa = "Sabuwa",
        Safana = "Safana",
        Sandamu = "Sandamu",
        Zango = "Zango"
    }
    export enum KebbiLGA  {
        Aleiro = "Aleiro",
        ArewaDandi = "Arewa Dandi",
        Argungu = "Argungu",
        Augie = "Augie",
        Bagudo = "Bagudo",
        BirninKebbi = "Birnin Kebbi",
        Bunza = "Bunza",
        Dandi = "Dandi",
        Fakai = "Fakai",
        Gwandu = "Gwandu",
        Jega = "Jega",
        KokoBesse = "Koko/Besse",
        Maiyama = "Maiyama",
        Ngaski = "Ngaski",
        Sakaba = "Sakaba",
        Shanga = "Shanga",
        Suru = "Suru",
        WasaguDanko = "Wasagu/Danko",
        Yauri = "Yauri",
        Zuru = "Zuru"
    }

    export enum KogiLGA {
        Adavi = "Adavi",
        Ajaokuta = "Ajaokuta",
        Ankpa = "Ankpa",
        Bassa = "Bassa",
        Dekina = "Dekina",
        Ibaji = "Ibaji",
        Idah = "Idah",
        IgalamelaOdolu = "Igalamela Odolu",
        Ijumu = "Ijumu",
        KabbaBunu = "Kabba/Bunu",
        Kogi = "Kogi",
        Lokoja = "Lokoja",
        MopaMuro = "Mopa-Muro",
        Ofu = "Ofu",
        OgoriMagongo = "Ogori/Magongo",
        Okehi = "Okehi",
        Okene = "Okene",
        Olamaboro = "Olamaboro",
        Omala = "Omala",
        YagbaEast = "Yagba East",
        YagbaWest = "Yagba West"
    }

    export enum KwaraLGA{
        Asa = "Asa",
        Baruten = "Baruten",
        Edu = "Edu",
        Ekiti = "Ekiti",
        Ifelodun = "Ifelodun",
        IlorinEast = "Ilorin East",
        IlorinSouth = "Ilorin South",
        IlorinWest = "Ilorin West",
        Irepodun = "Irepodun",
        Isin = "Isin",
        Kaiama = "Kaiama",
        Moro = "Moro",
        Offa = "Offa",
        OkeEro = "Oke Ero",
        Oyun = "Oyun",
        Pategi = "Pategi"
    }

    export enum LagosLGA {
        Agege = "Agege",
        AjeromiIfelodun = "Ajeromi-Ifelodun",
        Alimosho = "Alimosho",
        AmuwoOdofin = "Amuwo-Odofin",
        Apapa = "Apapa",
        Badagry = "Badagry",
        Epe = "Epe",
        EtiOsa = "Eti-Osa",
        IbejuLekki = "Ibeju-Lekki",
        IfakoIjaiye = "Ifako-Ijaiye",
        Ikeja = "Ikeja",
        Ikorodu = "Ikorodu",
        Kosofe = "Kosofe",
        LagosIsland = "Lagos Island",
        LagosMainland = "Lagos Mainland",
        Mushin = "Mushin",
        Ojo = "Ojo",
        OshodiIsolo = "Oshodi-Isolo",
        Somolu = "Somolu",
        Surulere = "Surulere"
    }

    export enum NasarawaLGA {
        Akwanga = "Akwanga",
        Awe = "Awe",
        Doma = "Doma",
        Karu = "Karu",
        Keana = "Keana",
        Keffi = "Keffi",
        Kokona = "Kokona",
        Lafia = "Lafia",
        Nasarawa = "Nasarawa",
        NasarawaEggon = "Nasarawa-Eggon",
        Obi = "Obi",
        Toto = "Toto",
        Wamba = "Wamba"
    }

    export enum NigerLGA {
        Agaie = "Agaie",
        Agwara = "Agwara",
        Bida = "Bida",
        Borgu = "Borgu",
        Bosso = "Bosso",
        Chanchaga = "Chanchaga",
        Edati = "Edati",
        Gbako = "Gbako",
        Gurara = "Gurara",
        Katcha = "Katcha",
        Kontagora = "Kontagora",
        Lapai = "Lapai",
        Lavun = "Lavun",
        Magama = "Magama",
        Mariga = "Mariga",
        Mashegu = "Mashegu",
        Mokwa = "Mokwa",
        Munya = "Munya",
        Paikoro = "Paikoro",
        Rafi = "Rafi",
        Rijau = "Rijau",
        Shiroro = "Shiroro",
        Suleja = "Suleja",
        Tafa = "Tafa",
        Wushishi = "Wushishi"
    }

    export enum OgunLGA  {
        AbeokutaNorth = "Abeokuta North",
        AbeokutaSouth = "Abeokuta South",
        AdoOdoOta = "Ado-Odo/Ota",
        EgbadoNorth = "Egbado North",
        EgbadoSouth = "Egbado South",
        Ewekoro = "Ewekoro",
        Ifo = "Ifo",
        IjebuEast = "Ijebu East",
        IjebuNorth = "Ijebu North",
        IjebuNorthEast = "Ijebu North-East",
        IjebuOde = "Ijebu Ode",
        Ikenne = "Ikenne",
        ImekoAfijo = "Imeko Afijo",
        Ipokia = "Ipokia",
        ObafemiOwode = "Obafemi Owode",
        Odeda = "Odeda",
        Odogbolu = "Odogbolu",
        OgunWaterside = "Ogun Waterside",
        RemoNorth = "Remo North",
        Sagamu = "Sagamu",
        YewaNorth = "Yewa North",
        YewaSouth = "Yewa South"
    }

    export enum OndoLGA {
        AkokoNorthEast = "Akoko North-East",
        AkokoNorthWest = "Akoko North-West",
        AkokoSouthEast = "Akoko South-East",
        AkokoSouthWest = "Akoko South-West",
        AkureNorth = "Akure North",
        AkureSouth = "Akure South",
        EseOdo = "Ese Odo",
        Idanre = "Idanre",
        Ifedore = "Ifedore",
        Ilaje = "Ilaje",
        IleOlujiOkeigbo = "Ile Oluji/Okeigbo",
        Irele = "Irele",
        Odigbo = "Odigbo",
        Okitipupa = "Okitipupa",
        OndoEast = "Ondo East",
        OndoWest = "Ondo West",
        Ose = "Ose",
        Owo = "Owo"
    }

    export enum OsunLGA {
        AtakunmosaEast = "Atakunmosa East",
        AtakunmosaWest = "Atakunmosa West",
        AyedaAde = "Ayeda Ade",
        Ayedire = "Ayedire",
        Boluwaduro = "Boluwaduro",
        Boripe = "Boripe",
        EdeNorth = "Ede North",
        EdeSouth = "Ede South",
        Egbedore = "Egbedore",
        Ejigbo = "Ejigbo",
        IfeCentral = "Ife Central",
        IfeEast = "Ife East",
        IfeNorth = "Ife North",
        IfeSouth = "Ife South",
        Ifedayo = "Ifedayo",
        Ifelodun = "Ifelodun",
        Ila = "Ila",
        IlesaEast = "Ilesa East",
        IlesaWest = "Ilesa West",
        Irepodun = "Irepodun",
        Irewole = "Irewole",
        Isokan = "Isokan",
        Iwo = "Iwo",
        Obokun = "Obokun",
        OdoOtIn = "Odo Otin",
        OlaOluwa = "Ola Oluwa",
        Olorunda = "Olorunda",
        Oriade = "Oriade",
        Orolu = "Orolu",
        Osogbo = "Osogbo"
    }
    export enum OyoLGA {
        Afijio = "Afijio",
        Akinyele = "Akinyele",
        Atiba = "Atiba",
        Atisbo = "Atisbo",
        Egbeda = "Egbeda",
        IbadanNorth = "Ibadan North",
        IbadanNorthEast = "Ibadan North-East",
        IbadanNorthWest = "Ibadan North-West",
        IbadanSouthEast = "Ibadan South-East",
        IbadanSouthWest = "Ibadan South-West",
        IbarapaCentral = "Ibarapa Central",
        IbarapaEast = "Ibarapa East",
        IbarapaNorth = "Ibarapa North",
        Ido = "Ido",
        Irepo = "Irepo",
        Iseyin = "Iseyin",
        Itesiwaju = "Itesiwaju",
        Iwajowa = "Iwajowa",
        Kajola = "Kajola",
        Lagelu = "Lagelu",
        OgbomoshoNorth = "Ogbomosho North",
        OgbomoshoSouth = "Ogbomosho South",
        OgoOluwa = "Ogo Oluwa",
        Oluyole = "Oluyole",
        OnaAra = "Ona Ara",
        Orelope = "Orelope",
        OriIre = "Ori Ire",
        OyoEast = "Oyo East",
        OyoWest = "Oyo West",
        SakiEast = "Saki East",
        SakiWest = "Saki West",
        Surulere = "Surulere"
    }

    export enum PlateauLGA {
        BarkinLadi = "Barkin Ladi",
        Bassa = "Bassa",
        Bokkos = "Bokkos",
        JosEast = "Jos East",
        JosNorth = "Jos North",
        JosSouth = "Jos South",
        Kanam = "Kanam",
        Kanke = "Kanke",
        LangtangNorth = "Langtang North",
        LangtangSouth = "Langtang South",
        Mangu = "Mangu",
        Mikang = "Mikang",
        Pankshin = "Pankshin",
        QuaAnPan = "Qua'an Pan",
        Riyom = "Riyom",
        Shendam = "Shendam",
        Wase = "Wase"
    }

    export enum RiversLGA {
        AbuaOdual = "Abua/Odual",
        AhoadaEast = "Ahoada East",
        AhoadaWest = "Ahoada West",
        AkukuToru = "Akuku-Toru",
        Andoni = "Andoni",
        AsariToru = "Asari-Toru",
        Bonny = "Bonny",
        Degema = "Degema",
        Eleme = "Eleme",
        Emohua = "Emohua",
        Etche = "Etche",
        Gokana = "Gokana",
        Ikwerre = "Ikwerre",
        Khana = "Khana",
        ObioAkpor = "Obio/Akpor",
        OgbaEgbemaNdoni = "Ogba/Egbema/Ndoni",
        OguBolo = "Ogu/Bolo",
        Okrika = "Okrika",
        Omuma = "Omuma",
        OpoboNkoro = "Opobo/Nkoro",
        Oyigbo = "Oyigbo",
        PortHarcourt = "Port Harcourt",
        Tai = "Tai"
    }
    export enum SokotoLGA {
        Binji = "Binji",
        Bodinga = "Bodinga",
        DangeShuni = "Dange Shuni",
        Gada = "Gada",
        Goronyo = "Goronyo",
        Gudu = "Gudu",
        Gwadabawa = "Gwadabawa",
        Illela = "Illela",
        Isa = "Isa",
        Kebbe = "Kebbe",
        Kware = "Kware",
        Rabah = "Rabah",
        SabonBirni = "Sabon Birni",
        Shagari = "Shagari",
        Silame = "Silame",
        SokotoNorth = "Sokoto North",
        SokotoSouth = "Sokoto South",
        Tambuwal = "Tambuwal",
        Tangaza = "Tangaza",
        Tureta = "Tureta",
        Wamako = "Wamako",
        Wurno = "Wurno",
        Yabo = "Yabo"
    }

    export enum TarabaLGA  {
        ArdoKola = "Ardo Kola",
        Bali = "Bali",
        Donga = "Donga",
        Gashaka = "Gashaka",
        Gassol = "Gassol",
        Ibi = "Ibi",
        Jalingo = "Jalingo",
        KarimLamido = "Karim Lamido",
        Kurmi = "Kurmi",
        Lau = "Lau",
        Sardauna = "Sardauna",
        Takum = "Takum",
        Ussa = "Ussa",
        Wukari = "Wukari",
        Yorro = "Yorro",
        Zing = "Zing"
    }
    export enum Yobe {
        Bade = "Bade",
        Bursari = "Bursari",
        Damaturu = "Damaturu",
        Fika = "Fika",
        Fune = "Fune",
        Geidam = "Geidam",
        Gujba = "Gujba",
        Gulani = "Gulani",
        Jakusko = "Jakusko",
        Karasuwa = "Karasuwa",
        Machina = "Machina",
        Nangere = "Nangere",
        Nguru = "Nguru",
        Potiskum = "Potiskum",
        Tarmuwa = "Tarmuwa",
        Yunusari = "Yunusari",
        Yusufari = "Yusufari"
    }
    
    export enum ZamfaraLGa {
        Anka = "Anka",
        Bakura = "Bakura",
        BirninMagajiKiyaw = "Birnin Magaji/Kiyaw",
        Bukkuyum = "Bukkuyum",
        Bungudu = "Bungudu",
        Chafe = "Chafe",
        Gummi = "Gummi",
        Gusau = "Gusau",
        KauraNamoda = "Kaura Namoda",
        Maradun = "Maradun",
        Maru = "Maru",
        Shinkafi = "Shinkafi",
        TalataMafara = "Talata Mafara",
        Tsafe = "Tsafe",
        Zurmi = "Zurmi"
    }

    export enum FCTLGA {
        Abaji = "Abaji",
        AbujaMunicipal = "Abuja Municipal",
        Bwari = "Bwari",
        Gwagwalada = "Gwagwalada",
        Kuje = "Kuje",
        Kwali = "Kwali"
    }

